# Generated by Django 4.1.6 on 2023-04-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_objecttypes_filter_as_and_more'),
        ('general', '0002_alter_geogentities_geog_entity_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_organisation_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_role_id', to='context.roletypes'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='role_class',
            field=models.ForeignKey(blank=True, db_column='role_class_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_role_class', to='context.roleclasses'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_type',
            field=models.ForeignKey(blank=True, db_column='user_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_user_type', to='context.rmsusertypes'),
        ),
    ]
