# Generated by Django 4.1.6 on 2023-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofiles_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='inverted_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='ocrid',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='prof_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
