# Generated by Django 4.1.6 on 2023-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofiles_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
