"""
Django settings for esbs project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from configs.app_settings import *
from configs.esbs_db_settings import *
from configs.identity_configs import CLIENT_ID, CLIENT_SECRET, AUTHORIZATION_ENDPOINT, TOKEN_ENDPOINT, USER_ENDPOINT
from configs.users_db_settings import *
from configs.context_db_settings import *
from configs.general_db_settings import *
from configs.rms_db_settings import *
from configs.mdm_db_settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET_APP_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ALLOWED_APP_HOSTS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_auth.registration',
    'drf_yasg',
    'context.apps.ContextConfig',
    'general.apps.GeneralConfig',
    'mdm.apps.MdmConfig',
    'rms.apps.RmsConfig',
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

AUTH_USER_MODEL = 'users.Users'

ROOT_URLCONF = 'esbs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esbs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    ESBS_DB_KEY_NAME: {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_ESBS_DB,
        'USER': DEV_PG_USER_ESBS_DB,
        'PASSWORD': DEV_PG_PASSWORD_ESBS_DB,
        'HOST': DEV_PG_HOST_ESBS_DB,
        'PORT': DEV_PG_PORT_ESBS_DB,
    },
    'sqlite_backup': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

DATABASE_ROUTERS = []


if not IS_CONTEXT_DB_CONSTRAINT:
    DATABASES[CONTEXT_DB_KEY_NAME] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_CONTEXT_DB,
        'USER': DEV_PG_USER_CONTEXT_DB,
        'PASSWORD': DEV_PG_PASSWORD_CONTEXT_DB,
        'HOST': DEV_PG_HOST_CONTEXT_DB,
        'PORT': DEV_PG_PORT_CONTEXT_DB,
    }
    DATABASE_ROUTERS.append('context.db_router.ContextDbRouter')

if not IS_GENERAL_DB_CONSTRAINT:
    DATABASES[GENERAL_DB_KEY_NAME] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_GENERAL_DB,
        'USER': DEV_PG_USER_GENERAL_DB,
        'PASSWORD': DEV_PG_PASSWORD_GENERAL_DB,
        'HOST': DEV_PG_HOST_GENERAL_DB,
        'PORT': DEV_PG_PORT_GENERAL_DB,
    }
    DATABASE_ROUTERS.append('general.db_router.GeneralDbRouter')

if not IS_RMS_DB_CONSTRAINT:
    DATABASES[RMS_DB_KEY_NAME] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_RMS_DB,
        'USER': DEV_PG_USER_RMS_DB,
        'PASSWORD': DEV_PG_PASSWORD_RMS_DB,
        'HOST': DEV_PG_HOST_RMS_DB,
        'PORT': DEV_PG_PORT_RMS_DB,
    }
    DATABASE_ROUTERS.append('rms.db_router.RmsDbRouter')

if not IS_MDM_DB_CONSTRAINT:
    DATABASES[MDM_DB_KEY_NAME] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_MDM_DB,
        'USER': DEV_PG_USER_MDM_DB,
        'PASSWORD': DEV_PG_PASSWORD_MDM_DB,
        'HOST': DEV_PG_HOST_MDM_DB,
        'PORT': DEV_PG_PORT_MDM_DB,
    }
    DATABASE_ROUTERS.append('mdm.db_router.MdmDbRouter')


if not IS_USERS_DB_CONSTRAINT:
    DATABASES[USERS_DB_KEY_NAME] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DEV_PG_DATABASE_USERS_DB,
        'USER': DEV_PG_USER_USERS_DB,
        'PASSWORD': DEV_PG_PASSWORD_USERS_DB,
        'HOST': DEV_PG_HOST_USERS_DB,
        'PORT': DEV_PG_PORT_USERS_DB,
    }
    DATABASE_ROUTERS.append('users.db_router.UsersDbRouter')


# REST FRAMEWORK SETTINGS
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAdminUser'
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
    'JSON_UNDERSCOREIZE': {
        'no_underscore_before_number': True,
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/?verification=1'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/?verification=1'

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "soiree.serializers.CustomUserDetailsSerializer",
}
REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "soiree.serializers.CustomRegisterSerializer",
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OIDC settings
# https://proxy.aai.lifescience-ri.eu/.well-known/openid-configuration

OIDC_DRF_AUTH_BACKEND = 'mozilla_django_oidc.auth.OIDCAuthenticationBackend'

OIDC_RP_CLIENT_ID = CLIENT_ID
OIDC_RP_CLIENT_SECRET = CLIENT_SECRET

OIDC_OP_AUTHORIZATION_ENDPOINT = AUTHORIZATION_ENDPOINT
OIDC_OP_TOKEN_ENDPOINT = TOKEN_ENDPOINT
OIDC_OP_USER_ENDPOINT = USER_ENDPOINT

OIDC_AUTH_REQUEST_EXTRA_PARAMS = {"code_challenge": "S256"}

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend'
)

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = SMTP_HOST
EMAIL_USE_TLS = True
EMAIL_PORT = SMTP_PORT
EMAIL_HOST_USER = SMTP_LOGIN
EMAIL_HOST_PASSWORD = SMTP_PASSWORD
