# Generated by Django 4.1.6 on 2023-04-20 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_objecttypes_filter_as_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetypes',
            name='applies_to',
        ),
        migrations.AddField(
            model_name='datetypes',
            name='applies_to_papers_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accessprereqtypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='accessprereqtypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkstatustypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='checkstatustypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compositehashtypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='compositehashtypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contributortypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='contributortypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datasetconsenttypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='datasetconsenttypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datasetdeidentificationlevels',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='datasetdeidentificationlevels',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datasetrecordkeytypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='datasetrecordkeytypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datetypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='datetypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='descriptiontypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='descriptiontypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doistatustypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='doistatustypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dtpstatustypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='dtpstatustypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dupstatustypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='dupstatustypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gendereligibilitytypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='gendereligibilitytypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='geogentitytypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='identifiertypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='identifiertypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='languageusagetypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='languageusagetypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='legalstatustypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='legalstatustypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='linktypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objectaccesstypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objectaccesstypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objectclasses',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objectclasses',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objectfiltertypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objectfiltertypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objectinstancetypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objectinstancetypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objectrelationshiptypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objectrelationshiptypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objecttypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='objecttypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orgattributedatatypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orgclasses',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orglinktypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='orglinktypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orgnamequalifiertypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orgrelationshiptypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prereqtypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='prereqtypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repoaccesstypes',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='repoaccesstypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rmsusertypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roleclasses',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roletypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sizeunits',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='sizeunits',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studyfeaturecategories',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='studyfeaturecategories',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studyfeaturetypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='studyfeaturetypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studyrelationshiptypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='studyrelationshiptypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studystatuses',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='studystatuses',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studytypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='studytypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timeunits',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='timeunits',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='titletypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='titletypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topictypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='topictypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topicvocabularies',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='topicvocabularies',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trialregistries',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='trialregistries',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertypes',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='usertypes',
            name='list_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
