# Generated by Django 4.1.6 on 2023-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_alter_accessprereqtypes_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprereqtypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='checkstatustypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='compositehashtypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='contributortypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='datasetconsenttypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='datasetdeidentificationlevels',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='datasetrecordkeytypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='datetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='descriptiontypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='doistatustypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='dtpstatustypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='dupstatustypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='gendereligibilitytypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='geogentitytypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='identifiertypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='languageusagetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='legalstatustypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='linktypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objectaccesstypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objectclasses',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objectfiltertypes',
            name='filter_as',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objectinstancetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objectrelationshiptypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='objecttypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgattributedatatypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgattributetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgclasses',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orglinktypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgnamequalifiertypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgrelationshiptypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='orgtypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='prereqtypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='repoaccesstypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='resourcetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='rmsusertypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='roleclasses',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='roletypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='sizeunits',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='studyfeaturecategories',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='studyfeaturetypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='studyrelationshiptypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='studystatuses',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='studytypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='timeunits',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='titletypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='topictypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='topicvocabularies',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='trialregistries',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='usertypes',
            name='name',
            field=models.CharField(db_index=True, max_length=75),
        ),
    ]
