# Generated by Django 4.1.6 on 2023-04-06 20:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataObjects',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sd_oid', models.CharField(blank=True, max_length=255, null=True)),
                ('display_title', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('access_details', models.CharField(blank=True, max_length=255, null=True)),
                ('access_details_url', models.URLField(blank=True, max_length=255, null=True)),
                ('url_last_checked', models.DateTimeField(blank=True, null=True)),
                ('add_study_contributors', models.BooleanField(blank=True, null=True)),
                ('add_study_topics', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
            ],
            options={
                'db_table': 'data_objects',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='MdrRecordChanges',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('Insert', 'Insert'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=15, null=True)),
                ('change_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mdr_record_changes',
                'ordering': ['-change_time'],
            },
        ),
        migrations.CreateModel(
            name='ObjectContributors',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_individual', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_contributors',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDatasets',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recordkey_details', models.TextField(blank=True, null=True)),
                ('deident_direct', models.BooleanField(default=False)),
                ('deident_hipaa', models.BooleanField(default=False)),
                ('deident_dates', models.BooleanField(default=False)),
                ('deident_kanon', models.BooleanField(default=False)),
                ('deident_nonarr', models.BooleanField(default=False)),
                ('deident_details', models.TextField(blank=True, null=True)),
                ('consent_noncommercial', models.BooleanField(default=False)),
                ('consent_geog_restrict', models.BooleanField(default=False)),
                ('consent_research_type', models.BooleanField(default=False)),
                ('consent_genetic_only', models.BooleanField(default=False)),
                ('consent_no_methods', models.BooleanField(default=False)),
                ('consent_details', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_datasets',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDates',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_is_range', models.BooleanField(default=False)),
                ('date_as_string', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_dates',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDescriptions',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_descriptions',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectIdentifiers',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('identifier_value', models.CharField(db_index=True, max_length=255)),
                ('identifier_date', models.DateTimeField(db_index=True, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_identifiers',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectInstances',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('url_last_checked', models.DateTimeField(blank=True, null=True)),
                ('resource_size', models.BigIntegerField(blank=True, null=True)),
                ('resource_comments', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_instances',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRelationships',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_relationships',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRights',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rights_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rights_url', models.URLField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_rights',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectTitles',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_text', models.CharField(db_index=True, max_length=255)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_titles',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectTopics',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mesh_coded', models.BooleanField(default=False)),
                ('mesh_code', models.CharField(blank=True, max_length=255, null=True)),
                ('mesh_value', models.CharField(blank=True, max_length=255, null=True)),
                ('original_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'object_topics',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sd_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('display_title', models.CharField(blank=True, max_length=255, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('data_sharing_statement', models.TextField(blank=True, null=True)),
                ('study_start_year', models.IntegerField(blank=True, null=True)),
                ('study_start_month', models.IntegerField(blank=True, null=True)),
                ('study_enrollment', models.CharField(blank=True, max_length=255, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'studies',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyContributors',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_individual', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_contributors',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyFeatures',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_features',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyIdentifiers',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('identifier_value', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier_date', models.DateTimeField(blank=True, null=True)),
                ('identifier_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_identifiers',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyRelationships',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_relationships',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyTitles',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_text', models.CharField(db_index=True, max_length=255)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_titles',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyTopics',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mesh_coded', models.BooleanField(default=False)),
                ('mesh_code', models.CharField(blank=True, max_length=255, null=True)),
                ('mesh_value', models.CharField(blank=True, max_length=255, null=True)),
                ('original_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'study_topics',
                'ordering': ['created_on'],
            },
        ),
    ]
