# Generated by Django 4.1.6 on 2023-02-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0001_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytopics',
            name='last_edited_by',
            field=models.ForeignKey(db_column='last_edited_by', on_delete=django.db.models.deletion.CASCADE, related_name='study_topics_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studytopics',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_topics_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studytopics',
            name='topic_type_id',
            field=models.ForeignKey(db_column='topic_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_topics_topic_type_id', to='context.topictypes'),
        ),
        migrations.AddField(
            model_name='studytitles',
            name='lang_code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AddField(
            model_name='studytitles',
            name='lang_usage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_lang_usage_id', to='context.languageusagetypes'),
        ),
        migrations.AddField(
            model_name='studytitles',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studytitles',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studytitles',
            name='title_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_title_type_id', to='context.titletypes'),
        ),
        migrations.AddField(
            model_name='studyrelationships',
            name='last_edited_by',
            field=models.ForeignKey(db_column='last_edited_by', on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyrelationships',
            name='relationship_type_id',
            field=models.ForeignKey(db_column='relationship_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_relationship_type_id', to='context.studyrelationshiptypes'),
        ),
        migrations.AddField(
            model_name='studyrelationships',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studyrelationships',
            name='target_study_id',
            field=models.ForeignKey(db_column='target_study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_target_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='identifier_org_id',
            field=models.ForeignKey(db_column='identifier_org_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_identifier_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='identifier_type_id',
            field=models.ForeignKey(db_column='identifier_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_identifier_type_id', to='context.identifiertypes'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studyfeatures',
            name='feature_type_id',
            field=models.ForeignKey(db_column='feature_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_features_feature_type_id', to='context.studyfeaturetypes'),
        ),
        migrations.AddField(
            model_name='studyfeatures',
            name='feature_value_id',
            field=models.ForeignKey(db_column='feature_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_features_feature_value_id', to='context.studyfeaturecategories'),
        ),
        migrations.AddField(
            model_name='studyfeatures',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_features_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyfeatures',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_features_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studycontributors',
            name='contributor_type_id',
            field=models.ForeignKey(db_column='contributor_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_contributor_type_id', to='context.contributortypes'),
        ),
        migrations.AddField(
            model_name='studycontributors',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studycontributors',
            name='organisation_id',
            field=models.ForeignKey(blank=True, db_column='organisation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_organisation_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='studycontributors',
            name='person_id',
            field=models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studycontributors',
            name='study_id',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='studies',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studies',
            name='max_age_unit_id',
            field=models.ForeignKey(blank=True, db_column='max_age_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_max_age_unit_id', to='context.timeunits'),
        ),
        migrations.AddField(
            model_name='studies',
            name='min_age_unit_id',
            field=models.ForeignKey(blank=True, db_column='min_age_unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_min_age_unit_id', to='context.timeunits'),
        ),
        migrations.AddField(
            model_name='studies',
            name='study_gender_elig_id',
            field=models.ForeignKey(blank=True, db_column='study_gender_elig_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_gender_elig_id', to='context.gendereligibilitytypes'),
        ),
        migrations.AddField(
            model_name='studies',
            name='study_status_id',
            field=models.ForeignKey(blank=True, db_column='study_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_status_id', to='context.studystatuses'),
        ),
        migrations.AddField(
            model_name='studies',
            name='study_type_id',
            field=models.ForeignKey(blank=True, db_column='study_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_type_id', to='context.studytypes'),
        ),
        migrations.AddField(
            model_name='studies',
            name='title_lang_code_id',
            field=models.ForeignKey(blank=True, db_column='title_lang_code_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_title_lang_code', to='general.languagecodes'),
        ),
        migrations.AddField(
            model_name='objecttopics',
            name='last_edited_by',
            field=models.ForeignKey(db_column='last_edited_by', on_delete=django.db.models.deletion.CASCADE, related_name='object_topics_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objecttopics',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_topics_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objecttopics',
            name='topic_type_id',
            field=models.ForeignKey(db_column='topic_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_topics_topic_type_id', to='context.topictypes'),
        ),
        migrations.AddField(
            model_name='objecttitles',
            name='lang_code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AddField(
            model_name='objecttitles',
            name='lang_usage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_lang_usage_id', to='context.languageusagetypes'),
        ),
        migrations.AddField(
            model_name='objecttitles',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objecttitles',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objecttitles',
            name='title_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_title_type_id', to='context.titletypes'),
        ),
        migrations.AddField(
            model_name='objectrights',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_rights_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectrights',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_rights_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectrelationships',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectrelationships',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectrelationships',
            name='relationship_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_relationship_type_id', to='context.objectrelationshiptypes'),
        ),
        migrations.AddField(
            model_name='objectrelationships',
            name='target_object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_target_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='instance_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_instance_type_id', to='context.objectinstancetypes'),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='repository_org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_repository_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='resource_size_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_resource_size_unit_id', to='context.sizeunits'),
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='resource_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_resource_type_id', to='context.resourcetypes'),
        ),
        migrations.AddField(
            model_name='objectidentifiers',
            name='identifier_org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_identifier_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='objectidentifiers',
            name='identifier_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_identifier_type_id', to='context.identifiertypes'),
        ),
        migrations.AddField(
            model_name='objectidentifiers',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectidentifiers',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectdescriptions',
            name='description_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_description_type_id', to='context.descriptiontypes'),
        ),
        migrations.AddField(
            model_name='objectdescriptions',
            name='lang_code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AddField(
            model_name='objectdescriptions',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectdescriptions',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectdates',
            name='date_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_dates_date_type_id', to='context.datetypes'),
        ),
        migrations.AddField(
            model_name='objectdates',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_dates_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectdates',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_dates_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectdatasets',
            name='consent_type_id',
            field=models.ForeignKey(db_column='consent_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_consent_type_id', to='context.datasetconsenttypes'),
        ),
        migrations.AddField(
            model_name='objectdatasets',
            name='deident_type_id',
            field=models.ForeignKey(db_column='deident_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_deident_type_id', to='context.datasetdeidentificationlevels'),
        ),
        migrations.AddField(
            model_name='objectdatasets',
            name='last_edited_by',
            field=models.ForeignKey(db_column='last_edited_by', on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectdatasets',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectdatasets',
            name='recordkey_type_id',
            field=models.ForeignKey(db_column='recordkey_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_recordkey_type_id', to='context.datasetrecordkeytypes'),
        ),
        migrations.AddField(
            model_name='objectcontributors',
            name='contributor_type_id',
            field=models.ForeignKey(db_column='contributor_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_contributor_type_id', to='context.contributortypes'),
        ),
        migrations.AddField(
            model_name='objectcontributors',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectcontributors',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='objectcontributors',
            name='organisation_id',
            field=models.ForeignKey(blank=True, db_column='organisation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_organisation_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='objectcontributors',
            name='person_id',
            field=models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mdrrecordchanges',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdr_record_changes_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='access_type_id',
            field=models.ForeignKey(blank=True, db_column='access_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_access_type_id', to='context.objectaccesstypes'),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='doi_status_id',
            field=models.ForeignKey(blank=True, db_column='doi_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_doi_status_id', to='context.doistatustypes'),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='lang_code_id',
            field=models.ForeignKey(blank=True, db_column='lang_code_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='managing_org_id',
            field=models.ForeignKey(blank=True, db_column='managing_org_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_managing_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='object_class_id',
            field=models.ForeignKey(blank=True, db_column='object_class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_object_class_id', to='context.objectclasses'),
        ),
        migrations.AddField(
            model_name='dataobjects',
            name='object_type_id',
            field=models.ForeignKey(blank=True, db_column='object_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_object_type_id', to='context.objecttypes'),
        ),
    ]
