# Generated by Django 4.1.6 on 2023-04-09 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0002_alter_objecttypes_filter_as_and_more'),
        ('general', '0002_alter_geogentities_geog_entity_type_and_more'),
        ('mdm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_access_type_id', to='context.objectaccesstypes'),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='doi_status',
            field=models.ForeignKey(blank=True, db_column='doi_status_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_doi_status_id', to='context.doistatustypes'),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='lang_code',
            field=models.ForeignKey(blank=True, db_column='lang_code_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='managing_org',
            field=models.ForeignKey(blank=True, db_column='managing_org_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_managing_org_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='object_class',
            field=models.ForeignKey(blank=True, db_column='object_class_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_object_class_id', to='context.objectclasses'),
        ),
        migrations.AlterField(
            model_name='dataobjects',
            name='object_type',
            field=models.ForeignKey(blank=True, db_column='object_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_object_type_id', to='context.objecttypes'),
        ),
        migrations.AlterField(
            model_name='mdrrecordchanges',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdr_record_changes_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectcontributors',
            name='contributor_type',
            field=models.ForeignKey(blank=True, db_column='contributor_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_contributor_type_id', to='context.contributortypes'),
        ),
        migrations.AlterField(
            model_name='objectcontributors',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectcontributors',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectcontributors',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_organisation_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='objectcontributors',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_contributors_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectdatasets',
            name='consent_type',
            field=models.ForeignKey(blank=True, db_column='consent_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_consent_type_id', to='context.datasetconsenttypes'),
        ),
        migrations.AlterField(
            model_name='objectdatasets',
            name='deident_type',
            field=models.ForeignKey(blank=True, db_column='deident_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_deident_type_id', to='context.datasetdeidentificationlevels'),
        ),
        migrations.AlterField(
            model_name='objectdatasets',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectdatasets',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectdatasets',
            name='recordkey_type',
            field=models.ForeignKey(blank=True, db_column='recordkey_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_datasets_recordkey_type_id', to='context.datasetrecordkeytypes'),
        ),
        migrations.AlterField(
            model_name='objectdates',
            name='date_type',
            field=models.ForeignKey(blank=True, db_column='date_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_dates_date_type_id', to='context.datetypes'),
        ),
        migrations.AlterField(
            model_name='objectdates',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_dates_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectdates',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_dates', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectdescriptions',
            name='description_type',
            field=models.ForeignKey(blank=True, db_column='description_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_description_type_id', to='context.descriptiontypes'),
        ),
        migrations.AlterField(
            model_name='objectdescriptions',
            name='lang_code',
            field=models.ForeignKey(blank=True, db_column='lang_code_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AlterField(
            model_name='objectdescriptions',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectdescriptions',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_descriptions', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectidentifiers',
            name='identifier_org',
            field=models.ForeignKey(blank=True, db_column='identifier_org_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_identifier_org_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='objectidentifiers',
            name='identifier_type',
            field=models.ForeignKey(blank=True, db_column='identifier_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_identifier_type_id', to='context.identifiertypes'),
        ),
        migrations.AlterField(
            model_name='objectidentifiers',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectidentifiers',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_identifiers', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='instance_type',
            field=models.ForeignKey(blank=True, db_column='instance_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_instance_type_id', to='context.objectinstancetypes'),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='repository_org',
            field=models.ForeignKey(blank=True, db_column='repository_org_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_repository_org_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='resource_size_unit',
            field=models.ForeignKey(blank=True, db_column='resource_size_unit_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_resource_size_unit_id', to='context.sizeunits'),
        ),
        migrations.AlterField(
            model_name='objectinstances',
            name='resource_type',
            field=models.ForeignKey(blank=True, db_column='resource_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances_resource_type_id', to='context.resourcetypes'),
        ),
        migrations.AlterField(
            model_name='objectrelationships',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectrelationships',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectrelationships',
            name='relationship_type',
            field=models.ForeignKey(blank=True, db_column='relationship_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_relationship_type_id', to='context.objectrelationshiptypes'),
        ),
        migrations.AlterField(
            model_name='objectrelationships',
            name='target_object_id',
            field=models.ForeignKey(blank=True, db_column='target_object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_target_object_id', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objectrights',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_rights_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectrights',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_rights', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objecttitles',
            name='lang_code',
            field=models.ForeignKey(blank=True, db_column='lang_code_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AlterField(
            model_name='objecttitles',
            name='lang_usage',
            field=models.ForeignKey(blank=True, db_column='lang_usage_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_lang_usage_id', to='context.languageusagetypes'),
        ),
        migrations.AlterField(
            model_name='objecttitles',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objecttitles',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_titles', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objecttitles',
            name='title_type',
            field=models.ForeignKey(blank=True, db_column='title_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_titles_title_type_id', to='context.titletypes'),
        ),
        migrations.AlterField(
            model_name='objecttopics',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_topics_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objecttopics',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_topics', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='objecttopics',
            name='topic_type',
            field=models.ForeignKey(blank=True, db_column='topic_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_topics_topic_type_id', to='context.topictypes'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studies',
            name='max_age_unit',
            field=models.ForeignKey(blank=True, db_column='max_age_unit_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_max_age_unit_id', to='context.timeunits'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='min_age_unit',
            field=models.ForeignKey(blank=True, db_column='min_age_unit_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_min_age_unit_id', to='context.timeunits'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_gender_elig',
            field=models.ForeignKey(blank=True, db_column='study_gender_elig_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_gender_elig_id', to='context.gendereligibilitytypes'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_status',
            field=models.ForeignKey(blank=True, db_column='study_status_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_status_id', to='context.studystatuses'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='study_type',
            field=models.ForeignKey(blank=True, db_column='study_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_type_id', to='context.studytypes'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='title_lang_code',
            field=models.ForeignKey(blank=True, db_column='title_lang_code_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_title_lang_code', to='general.languagecodes'),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='contributor_type',
            field=models.ForeignKey(blank=True, db_column='contributor_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_contributor_type_id', to='context.contributortypes'),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_organisation_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_contributors', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studyfeatures',
            name='feature_type',
            field=models.ForeignKey(blank=True, db_column='feature_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_features_feature_type_id', to='context.studyfeaturetypes'),
        ),
        migrations.AlterField(
            model_name='studyfeatures',
            name='feature_value',
            field=models.ForeignKey(blank=True, db_column='feature_value_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_features_feature_value_id', to='context.studyfeaturecategories'),
        ),
        migrations.AlterField(
            model_name='studyfeatures',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_features_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyfeatures',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_features', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='identifier_org',
            field=models.ForeignKey(blank=True, db_column='identifier_org_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_identifier_org_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='identifier_type',
            field=models.ForeignKey(blank=True, db_column='identifier_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_identifier_type_id', to='context.identifiertypes'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_identifiers', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studyrelationships',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyrelationships',
            name='relationship_type',
            field=models.ForeignKey(blank=True, db_column='relationship_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_relationship_type_id', to='context.studyrelationshiptypes'),
        ),
        migrations.AlterField(
            model_name='studyrelationships',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studyrelationships',
            name='target_study_id',
            field=models.ForeignKey(blank=True, db_column='target_study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_target_study_id', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studytitles',
            name='lang_code',
            field=models.ForeignKey(blank=True, db_column='lang_code_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_lang_code_id', to='general.languagecodes'),
        ),
        migrations.AlterField(
            model_name='studytitles',
            name='lang_usage',
            field=models.ForeignKey(blank=True, db_column='lang_usage_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_lang_usage_id', to='context.languageusagetypes'),
        ),
        migrations.AlterField(
            model_name='studytitles',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studytitles',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_titles', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studytitles',
            name='title_type',
            field=models.ForeignKey(blank=True, db_column='title_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_titles_title_type_id', to='context.titletypes'),
        ),
        migrations.AlterField(
            model_name='studytopics',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_topics_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studytopics',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_topics', to='mdm.studies'),
        ),
        migrations.AlterField(
            model_name='studytopics',
            name='topic_type',
            field=models.ForeignKey(blank=True, db_column='topic_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_topics_topic_type_id', to='context.topictypes'),
        ),
    ]
