# Generated by Django 4.1.6 on 2023-04-06 20:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransferAccesses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('conforms_to_default', models.BooleanField(default=False)),
                ('variations', models.TextField(blank=True, null=True)),
                ('dta_file_path', models.TextField(blank=True, null=True)),
                ('repo_signature_1', models.IntegerField(default=0)),
                ('repo_signature_2', models.IntegerField(default=0)),
                ('provider_signature_1', models.IntegerField(default=0)),
                ('provider_signature_2', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'data_transfer_accesses',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DataTransferProcesses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_contact_date', models.DateTimeField(blank=True, null=True)),
                ('set_up_complete_date', models.DateTimeField(blank=True, null=True)),
                ('md_access_granted_date', models.DateTimeField(blank=True, null=True)),
                ('md_complete_date', models.DateTimeField(blank=True, null=True)),
                ('dta_agreed_date', models.DateTimeField(blank=True, null=True)),
                ('upload_access_requested_date', models.DateTimeField(blank=True, null=True)),
                ('upload_access_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('upload_complete_date', models.DateTimeField(blank=True, null=True)),
                ('qc_checks_complete_date', models.DateTimeField(blank=True, null=True)),
                ('md_integrated_with_mdr_date', models.DateTimeField(blank=True, null=True)),
                ('availability_requested_date', models.DateTimeField(blank=True, null=True)),
                ('availability_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'data_transfer_processes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DataUseAccesses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conforms_to_default', models.BooleanField(db_index=True, default=False)),
                ('variations', models.TextField(blank=True, null=True)),
                ('repo_is_proxy_provider', models.BooleanField(db_index=True, default=False)),
                ('dua_file_path', models.TextField(blank=True, null=True)),
                ('repo_signatory_1', models.IntegerField(blank=True, null=True)),
                ('repo_signatory_2', models.IntegerField(blank=True, null=True)),
                ('provider_signatory_1', models.IntegerField(blank=True, null=True)),
                ('provider_signatory_2', models.IntegerField(blank=True, null=True)),
                ('requester_signatory_1', models.IntegerField(blank=True, null=True)),
                ('requester_signatory_2', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'data_use_accesses',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DataUseProcesses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_contact_date', models.DateTimeField(blank=True, null=True)),
                ('set_up_completed_date', models.DateTimeField(blank=True, null=True)),
                ('prereqs_met_date', models.DateTimeField(blank=True, null=True)),
                ('dua_agreed_date', models.DateTimeField(blank=True, null=True)),
                ('availability_requested_date', models.DateTimeField(blank=True, null=True)),
                ('availability_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('access_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'data_use_processes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpDatasets',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('legal_status_text', models.TextField(blank=True, null=True)),
                ('legal_status_path', models.TextField(blank=True, null=True)),
                ('desc_md_check_status_date', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('deident_check_status_date', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_datasets',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpNotes',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_notes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpObjects',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_dataset', models.BooleanField(default=False)),
                ('download_allowed', models.BooleanField(default=False)),
                ('access_details', models.TextField(blank=True, null=True)),
                ('embargo_requested', models.BooleanField(default=False)),
                ('embargo_regime', models.TextField(blank=True, null=True)),
                ('embargo_still_applies', models.BooleanField(default=False)),
                ('access_check_date', models.DateTimeField(blank=True, null=True)),
                ('md_check_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_objects',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpPeople',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_people',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpPrereqs',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prereq_notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_prereqs',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DtpStudies',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('md_check_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dtp_studies',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupNotes',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_notes',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupObjects',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_objects',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupPeople',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_people',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupPrereqs',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prereq_notes', models.TextField(blank=True, null=True)),
                ('prereq_met', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_prereqs',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupSecondaryUse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('secondary_use_summary', models.TextField(blank=True, null=True)),
                ('publication', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('attribution_present', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_secondary_use',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='DupStudies',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'dup_studies',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='RmsRecordChanges',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('Insert', 'Insert'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=15, null=True)),
                ('change_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rms_record_changes',
                'ordering': ['-change_time'],
            },
        ),
    ]
