# Generated by Django 4.1.6 on 2023-04-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm', '0002_initial'),
        ('general', '0001_initial'),
        ('context', '0001_initial'),
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmsrecordchanges',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rms_record_changes_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dupstudies',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_studies_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='dupstudies',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_studies_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='dupsecondaryuse',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_secondary_use_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='dupprereqs',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_prereqs_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='dupprereqs',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_prereqs_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='dupprereqs',
            name='prereq_type',
            field=models.ForeignKey(blank=True, db_column='prereq_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_prereqs_prereq_id', to='context.accessprereqtypes'),
        ),
        migrations.AddField(
            model_name='duppeople',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_people_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='duppeople',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_people_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dupobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects_access_type_id', to='context.accessprereqtypes'),
        ),
        migrations.AddField(
            model_name='dupobjects',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='dupobjects',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='dupnotes',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_notes_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dupnotes',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_notes_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='dtpstudies',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_studies_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtpstudies',
            name='md_check_by',
            field=models.ForeignKey(blank=True, db_column='md_check_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_studies_md_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpstudies',
            name='md_check_status',
            field=models.ForeignKey(blank=True, db_column='md_check_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_studies_md_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpstudies',
            name='study_id',
            field=models.ForeignKey(blank=True, db_column='study_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_studies_study_id', to='mdm.studies'),
        ),
        migrations.AddField(
            model_name='dtpprereqs',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_prereqs_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtpprereqs',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_prereqs_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='dtpprereqs',
            name='prereq_type',
            field=models.ForeignKey(blank=True, db_column='prereq_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_prereqs_prereq_type_id', to='context.accessprereqtypes'),
        ),
        migrations.AddField(
            model_name='dtppeople',
            name='dtp_id',
            field=models.ForeignKey(db_column='dtp_id', db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_people_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtppeople',
            name='person',
            field=models.ForeignKey(db_column='person_id', db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_people_person_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='access_check_by',
            field=models.ForeignKey(blank=True, db_column='access_check_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_access_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='access_check_status',
            field=models.ForeignKey(blank=True, db_column='access_check_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_access_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_access_type_id', to='context.objectaccesstypes'),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='md_check_by',
            field=models.ForeignKey(blank=True, db_column='md_check_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_md_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='md_check_status',
            field=models.ForeignKey(blank=True, db_column='md_check_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_md_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpobjects',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='dtpnotes',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dtp_notes_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpnotes',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_notes_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='deident_check_by',
            field=models.ForeignKey(blank=True, db_column='deident_check_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_deident_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='deident_check_status',
            field=models.ForeignKey(blank=True, db_column='deident_check_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_deident_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='desc_md_check_by',
            field=models.ForeignKey(blank=True, db_column='desc_md_check_by', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_desc_md_check_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='desc_md_check_status',
            field=models.ForeignKey(blank=True, db_column='desc_md_check_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_desc_md_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_dtp_id', to='rms.datatransferprocesses'),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='legal_status',
            field=models.ForeignKey(blank=True, db_column='legal_status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_legal_status_id', to='context.legalstatustypes'),
        ),
        migrations.AddField(
            model_name='dtpdatasets',
            name='object_id',
            field=models.ForeignKey(blank=True, db_column='object_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_datasets_object_id', to='mdm.dataobjects'),
        ),
        migrations.AddField(
            model_name='datauseprocesses',
            name='org_id',
            field=models.ForeignKey(blank=True, db_column='org_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='datauseprocesses',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dup_status_id', to='context.dupstatustypes'),
        ),
        migrations.AddField(
            model_name='datauseaccesses',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_dup_id', to='rms.datauseprocesses'),
        ),
        migrations.AddField(
            model_name='datatransferprocesses',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_org_id', to='general.organisations'),
        ),
        migrations.AddField(
            model_name='datatransferprocesses',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_status_id', to='context.dtpstatustypes'),
        ),
        migrations.AddField(
            model_name='datatransferaccesses',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dta_dtp_id', to='rms.datatransferprocesses'),
        ),
    ]
