# Generated by Django 4.1.6 on 2023-04-06 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeogEntities',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=75, unique=True)),
                ('code', models.CharField(db_index=True, max_length=75, null=True)),
                ('parent', models.CharField(db_index=True, max_length=75, null=True)),
                ('old_id', models.IntegerField(null=True)),
                ('geog_entity_type', models.ForeignKey(db_column='type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geog_entities_type_id', to='context.geogentitytypes')),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geog_entities_parent_id', to='general.geogentities')),
            ],
            options={
                'db_table': 'geog_entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageCodes',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('language_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('marc_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('lang_name_en', models.CharField(db_index=True, max_length=50)),
                ('lang_name_fr', models.CharField(db_index=True, max_length=50)),
                ('lang_name_de', models.CharField(db_index=True, max_length=50)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'language_codes',
                'ordering': ['language_code', 'lang_name_en'],
            },
        ),
        migrations.CreateModel(
            name='MeshLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('term', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'mesh_lookup',
            },
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('default_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ror_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('display_suffix', models.CharField(db_index=True, max_length=255, null=True)),
                ('scope_id', models.IntegerField(db_index=True, null=True)),
                ('scope_notes', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('year_established', models.IntegerField(db_index=True, null=True)),
                ('year_ceased', models.IntegerField(db_index=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=50, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['default_name'],
            },
        ),
        migrations.CreateModel(
            name='PublishedJournals',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pisnn', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('eisnn', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('additional_issns', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'published_journals',
            },
        ),
        migrations.CreateModel(
            name='OrgTypeMembership',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('org_type', models.ForeignKey(blank=True, db_column='org_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_type_membership_org_type_id', to='context.orgtypes')),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_type_membership_org_id', to='general.organisations')),
            ],
            options={
                'db_table': 'org_type_membership',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrgRelationships',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('year_established', models.IntegerField(blank=True, db_index=True, null=True)),
                ('year_ceased', models.IntegerField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_relationships_org_id', to='general.organisations')),
                ('relationship_type', models.ForeignKey(blank=True, db_column='relationship_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_relationships_relationship_type_id', to='context.orgrelationshiptypes')),
                ('target_org', models.ForeignKey(blank=True, db_column='target_org_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_relationships_target_org_id', to='general.organisations')),
            ],
            options={
                'db_table': 'org_relationships',
            },
        ),
        migrations.CreateModel(
            name='OrgNames',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('script_code', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('changes_language', models.ForeignKey(blank=True, db_column='changes_language_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_names_changes_language', to='general.languagecodes')),
                ('lang_code', models.ForeignKey(blank=True, db_column='lang_code_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_names_lang_code_id', to='general.languagecodes')),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_names_org_id', to='general.organisations')),
                ('qualifier', models.ForeignKey(blank=True, db_column='qualifier_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_names_qualifier_id', to='context.orgnamequalifiertypes')),
            ],
            options={
                'db_table': 'org_names',
            },
        ),
        migrations.CreateModel(
            name='OrgLocations',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=11, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_locations_city_id', to='general.geogentities')),
                ('country', models.ForeignKey(blank=True, db_column='country_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_locations_country_id', to='general.geogentities')),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_locations_org_id', to='general.organisations')),
            ],
            options={
                'db_table': 'org_locations',
            },
        ),
        migrations.CreateModel(
            name='OrgLinks',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('org_link_type', models.ForeignKey(blank=True, db_column='org_link_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_links_org_link_type', to='context.orglinktypes')),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_links_org_id', to='general.organisations')),
            ],
            options={
                'db_table': 'org_links',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrgAttributes',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attribute_string_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attribute_integer_value', models.IntegerField(blank=True, db_index=True, null=True)),
                ('attribute_boolean_value', models.BooleanField(blank=True, db_index=True, null=True)),
                ('attribute_date_value', models.DateField(blank=True, db_index=True, null=True)),
                ('attribute_float_value', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('attribute_type', models.ForeignKey(blank=True, db_column='attribute_type_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_attributes_attribute_type_id', to='context.orgattributetypes')),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_attributes_org_id', to='general.organisations')),
            ],
            options={
                'db_table': 'org_attributes',
                'ordering': ['created_on'],
            },
        ),
    ]
