# Generated by Django 4.1.6 on 2023-02-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgattributes',
            old_name='attribute_type_id',
            new_name='attribute_type',
        ),
        migrations.RenameField(
            model_name='orgattributes',
            old_name='org_id',
            new_name='organisation',
        ),
    ]
