# Generated by Django 4.1.6 on 2023-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_geogentities_geog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meshlookup',
            name='entry',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
