# Generated by Django 4.1.6 on 2023-04-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_meshlookup_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='ror_id',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
