# Generated by Django 4.1.6 on 2023-04-20 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_organisations_default_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
