# Generated by Django 4.1.6 on 2023-04-20 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_organisations_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geogentities',
            name='code',
            field=models.CharField(db_index=True, max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='geogentities',
            name='name',
            field=models.CharField(db_index=True, max_length=375, unique=True),
        ),
        migrations.AlterField(
            model_name='geogentities',
            name='parent',
            field=models.CharField(db_index=True, max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='languagecodes',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
