# Generated by Django 4.1.6 on 2023-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_geogentities_code_alter_geogentities_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geogentities',
            name='name',
            field=models.CharField(db_index=True, max_length=375),
        ),
    ]
